export type Product = {
  id: string;
  name: string;
  blurb: string;
  img: string;
  price: number;
  link: string;
  category: "cosmetics" | "home-decor" | "water-bottles" | "aesthetic";
  rating: number;
  reviews: number;
};

export const products: Product[] = [
  {
    id: "1",
    name: "Chaun Legend Nail Polish",
    blurb:
      "Striking color with a mirror-gloss finish that refuses to fade. One swipe, and your nails look unapologetically expensive.",
    img: "/assets/images/nails.webp",
    price: 18,
    link: "/product/1",
    category: "cosmetics",
    rating: 4.5,
    reviews: 12,
  },
  {
    id: "2",
    name: "Swiss Miss Nail Polish Pack",
    blurb:
      "A power set of everyday shades built to elevate your hands instantly. Smooth, flawless, and effortlessly classy.",
    img: "/assets/images/swiss.webp",
    price: 28,
    link: "/product/2",
    category: "cosmetics",
    rating: 4.8,
    reviews: 30,
  },
  {
    id: "3",
    name: "Fogg Perfume Gift Pack",
    blurb:
      "A bold, all-day signature scent that turns heads without trying. Warm, commanding, and unmistakably present.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzrRjNb8FIqHIf0twg9ATF8zlDs0_PDJ8ClQ&s",
    price: 22,
    link: "/product/3",
    category: "cosmetics",
    rating: 3.9,
    reviews: 8,
  },
  {
    id: "4",
    name: "Deep Clean Facewash",
    blurb:
      "A refreshing detox for your skin that wipes away dullness on contact. Clean, crisp, and instantly invigorating.",
    img: "/assets/images/421.jpg",
    price: 14,
    link: "/product/4",
    category: "cosmetics",
    rating: 4.2,
    reviews: 22,
  },

  {
    id: "6",
    name: "Moonlit Linen Room Spray",
    blurb:
      "A calming, slow-burning fragrance that settles your space into a hushed, luxurious mood instantly.",
    img: "/assets/images/linen.webp",
    price: 24,
    link: "/product/6",
    category: "home-decor",
    rating: 4.7,
    reviews: 15,
  },

  {
    id: "7",
    name: "Soft Bloom Body Mist",
    blurb:
      "Lightweight, airy, and intimate. A daily mist that feels like stepping into soft morning sun.",
    img: "/assets/images/mist.jpg",
    price: 19,
    link: "/product/7",
    category: "cosmetics",
    rating: 5.0,
    reviews: 5,
  },
  {
    id: "8",
    name: "White Tea Calming Soap Bar",
    blurb:
      "Hand-pressed and cold-crafted. A clean, silky lather that leaves your skin quietly refreshed.",
    img: "/assets/images/soap.webp",
    price: 9,
    link: "/product/8",
    category: "cosmetics",
    rating: 3.5,
    reviews: 40,
  },

  {
    id: "9",
    name: "Almond Milk Body Lotion",
    blurb:
      "Deeply hydrating with a soft, sweet finish. The kind of lotion that makes you touch your arm twice.",
    img: "/assets/images/lotion.webp",
    price: 21,
    link: "/product/9",
    category: "cosmetics",
    rating: 4.6,
    reviews: 28,
  },
  {
    id: "10",
    name: "Silk Comfort Scrub",
    blurb:
      "A velvety micro-scrub that gently renews your skin without scratching its peace.",
    img: "/assets/images/scrub.webp",
    price: 17,
    link: "/product/10",
    category: "cosmetics",
    rating: 4.1,
    reviews: 10,
  },
  {
    id: "11",
    name: "Rosewater Glow Toner",
    blurb:
      "A cool, hydrating splash that resets your skin and restores a soft, natural brightness.",
    img: "/assets/images/toner.webp",
    price: 20,
    link: "/product/11",
    category: "cosmetics",
    rating: 4.9,
    reviews: 35,
  },
  {
    id: "12",
    name: "Coconut Silk Hair Serum",
    blurb:
      "Smooths, softens, and adds that quiet, expensive gloss your hair never shuts up about.",
    img: "/assets/images/serum.webp",
    price: 26,
    link: "/product/12",
    category: "cosmetics",
    rating: 4.3,
    reviews: 18,
  },
  {
    id: "13",
    name: "Marble Ceramic Vase",
    blurb:
      "A sculptural piece that holds flowers and moments in equal measure. Timeless elegance for any room.",
    img: "/assets/images/vase.avif",
    price: 45,
    link: "/product/13",
    category: "home-decor",
    rating: 4.8,
    reviews: 9,
  },
  {
    id: "14",
    name: "Gold Brass Candle Holder",
    blurb:
      "Minimalist design that catches candlelight just right. A quiet statement piece for your space.",
    img: "/assets/images/candle.jpg",
    price: 32,
    link: "/product/14",
    category: "home-decor",
    rating: 3.8,
    reviews: 14,
  },
  {
    id: "15",
    name: "Woven Rattan Wall Hanging",
    blurb:
      "Handcrafted texture that brings warmth to any wall. Boho-inspired, forever fresh.",
    img: "/assets/images/ratan.avif",
    price: 38,
    link: "/product/15",
    category: "home-decor",
    rating: 4.4,
    reviews: 25,
  },
  {
    id: "16",
    name: "Minimalist Stainless Steel Water Bottle",
    blurb:
      "Keeps your drink at the perfect temperature for 24 hours. Sleek design, serious performance.",
    img: "/assets/images/water.webp",
    price: 35,
    link: "/product/16",
    category: "water-bottles",
    rating: 4.7,
    reviews: 32,
  },
  {
    id: "17",
    name: "Pastel Ombre Water Bottle",
    blurb:
      "A gradient dream that looks as good as it hydrates. Double-walled insulation, endless style.",
    img: "/assets/images/pastel.webp",
    price: 28,
    link: "/product/17",
    category: "water-bottles",
    rating: 4.0,
    reviews: 6,
  },
  {
    id: "18",
    name: "Vintage Glass Water Bottle with Cork",
    blurb:
      "Eco-conscious elegance. Borosilicate glass that feels timeless in your hand.",
    img: "/assets/images/cork.webp",
    price: 24,
    link: "/product/18",
    category: "water-bottles",
    rating: 4.5,
    reviews: 20,
  },
  {
    id: "19",
    name: "Botanical Dried Flower Frame",
    blurb:
      "Pressed blooms preserved in a light wood frame. Nature's art, frozen in time.",
    img: "/assets/images/frame.jpg",
    price: 42,
    link: "/product/19",
    category: "aesthetic",
    rating: 4.9,
    reviews: 11,
  },
  {
    id: "20",
    name: "Curved Ceramic Planter",
    blurb:
      "Soft, organic shapes that cradle your plants like sculptures. Blush pink glaze on cream clay.",
    img: "/assets/images/planter.webp",
    price: 29,
    link: "/product/20",
    category: "aesthetic",
    rating: 3.7,
    reviews: 7,
  },
  {
    id: "21",
    name: "Silk Eye Mask Sleep Set",
    blurb:
      "Luxe sleep ritual. Pure mulberry silk that glides against your skin and keeps you cool.",
    img: "/assets/images/eye.jpg",
    price: 33,
    link: "/product/21",
    category: "aesthetic",
    rating: 4.6,
    reviews: 38,
  },
  {
    id: "22",
    name: "Beaded Infinity Scarf",
    blurb:
      "Handwoven with tiny beads that catch light softly. A timeless accessory for any season.",
    img: "/assets/images/scarf.webp",
    price: 31,
    link: "/product/22",
    category: "aesthetic",
    rating: 4.2,
    reviews: 16,
  },
  {
    id: "23",
    name: "Lavender Pillow Mist",
    blurb:
      "A soft spritz before bed. Calming lavender that whispers you to sleep instantly.",
    img: "/assets/images/linen.webp",
    price: 16,
    link: "/product/23",
    category: "cosmetics",
    rating: 4.8,
    reviews: 29,
  },
  {
    id: "24",
    name: "Rose Quartz Facial Roller",
    blurb:
      "Cool stone that depuffs and sculpts. A morning ritual that feels like spa day.",
    img: "/assets/images/roller.webp",
    price: 19,
    link: "/product/24",
    category: "cosmetics",
    rating: 4.3,
    reviews: 13,
  },
  {
    id: "25",
    name: "Velvet Matte Lipstick Set",
    blurb:
      "A trio of deep reds and soft nudes with a finish that feels like cashmere.",
    img: "/assets/images/lipstick.png",
    price: 24,
    link: "/product/25",
    category: "cosmetics",
    rating: 4.5,
    reviews: 21,
  },
  {
    id: "26",
    name: "Golden Hour Shimmer Oil",
    blurb:
      "Infused with real gold flakes for a sun-kissed glow that lasts all day.",
    img: "/assets/images/shimmer-oil.png",
    price: 26,
    link: "/product/26",
    category: "cosmetics",
    rating: 4.1,
    reviews: 39,
  },
  {
    id: "27",
    name: "Abstract Geometric Art Print",
    blurb:
      "Modern lines meets soft pastels. A conversation starter for your gallery wall.",
    img: "/assets/images/art-print.png",
    price: 35,
    link: "/product/27",
    category: "aesthetic",
    rating: 4.7,
    reviews: 8,
  },
  {
    id: "28",
    name: "Terra Cotta Succulent Pot",
    blurb:
      "Hand-thrown clay with a raw, earthy texture. The perfect home for your green friends.",
    img: "/assets/images/succulent.png",
    price: 18,
    link: "/product/28",
    category: "home-decor",
    rating: 3.6,
    reviews: 19,
  },
  {
    id: "29",
    name: "Luxe Silk Pillowcase",
    blurb:
      "Wake up with smoother hair and skin. Champagne gold mulberry silk that feels like pure luxury.",
    img: "/assets/images/silk-pillowcase.png",
    price: 45,
    link: "/product/29",
    category: "aesthetic",
    rating: 4.9,
    reviews: 31,
  },
  {
    id: "30",
    name: "Crystal Infusion Water Bottle",
    blurb:
      "Charge your water with positive energy. Rose quartz infusion point in a sleek glass design.",
    img: "/assets/images/crystal-bottle.png",
    price: 38,
    link: "/product/30",
    category: "water-bottles",
    rating: 4.4,
    reviews: 24,
  },
  {
    id: "31",
    name: "Signature Gold Perfume",
    blurb:
      "A rich, long-lasting fragrance with notes of amber and vanilla. Pure luxury in a bottle.",
    img: "/assets/images/perfume.png",
    price: 85,
    link: "/product/31",
    category: "cosmetics",
    rating: 4.8,
    reviews: 15,
  },
  {
    id: "32",
    name: "Matte Steel Bottle",
    blurb:
      "Industrial strength hydration with a soft-touch finish. Keeps water cold for 12 hours.",
    img: "/assets/images/bottle.jpg",
    price: 40,
    link: "/product/32",
    category: "water-bottles",
    rating: 4.2,
    reviews: 27,
  },
  {
    id: "33",
    name: "French Lavender Bundle",
    blurb:
      "Real dried lavender from Provence. Adds a calming scent and rustic charm to any room.",
    img: "/assets/images/lavendar.jpg",
    price: 22,
    link: "/product/33",
    category: "home-decor",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: "34",
    name: "Crystal Glass Teapot",
    blurb:
      "A minimal borosilicate glass teapot that lets your blooming tea take center stage.",
    img: "/assets/images/glass-teapot.png",
    price: 45,
    link: "/product/34",
    category: "home-decor",
    rating: 4.8,
    reviews: 12,
  },
  {
    id: "35",
    name: "Minimalist Concrete Clock",
    blurb: "Raw concrete meets warm copper. A quiet guardian of your time.",
    img: "/assets/images/concrete-clock.png",
    price: 38,
    link: "/product/35",
    category: "home-decor",
    rating: 4.6,
    reviews: 8,
  },
  {
    id: "36",
    name: "Vintage Leather Journal",
    blurb:
      "Hand-bound soft leather with cream pages. For thoughts that deserve a permanent home.",
    img: "/assets/images/leather-journal.png",
    price: 32,
    link: "/product/36",
    category: "aesthetic",
    rating: 4.9,
    reviews: 25,
  },
  {
    id: "37",
    name: "Abstract Wave Phone Case",
    blurb:
      "A protective shell that doubles as art. Soft matte finish with organic wave patterns.",
    img: "/assets/images/abstract-phone-case.png",
    price: 24,
    link: "/product/37",
    category: "aesthetic",
    rating: 4.4,
    reviews: 18,
  },
  {
    id: "38",
    name: "Honey & Oat Face Mask",
    blurb:
      "Deeply nourishing and gentle. The comfort food your skin has been craving.",
    img: "/assets/images/honey-oat-mask.png",
    price: 22,
    link: "/product/38",
    category: "cosmetics",
    rating: 4.7,
    reviews: 30,
  },
  {
    id: "39",
    name: "Ceremonial Matcha Set",
    blurb:
      "A complete ritual in a box. Authentic whisk, scoop, and bowl for the perfect meditative brew.",
    img: "https://images.unsplash.com/photo-1639390167093-9c62311fe84d?auto=format&fit=crop&q=80&w=800",
    price: 85,
    link: "/product/39",
    category: "aesthetic",
    rating: 4.9,
    reviews: 14,
  },
  {
    id: "40",
    name: "Pressed Fern Frame",
    blurb:
      "Real fern fronds preserved in glass. A fragment of the forest for your quiet corner.",
    img: "https://images.unsplash.com/photo-1676889305533-0fd1767690ae?auto=format&fit=crop&q=80&w=800",
    price: 42,
    link: "/product/40",
    category: "home-decor",
    rating: 4.7,
    reviews: 14,
  },
  {
    id: "41",
    name: "Smoked Oak Candle",
    blurb:
      "A heavy glass vessel filled with the scent of woodsmoke and rain. Burns for 60 hours.",
    img: "https://images.unsplash.com/photo-1761162211100-f579e435452a?auto=format&fit=crop&q=80&w=800",
    price: 34,
    link: "/product/41",
    category: "home-decor",
    rating: 4.5,
    reviews: 32,
  },
  {
    id: "42",
    name: "Nordic Clay Vase",
    blurb:
      "Hand-turned clay with a textured, raw finish. Perfect for dried stems or standing alone.",
    img: "https://images.unsplash.com/photo-1652081489531-95f8b855bce3?auto=format&fit=crop&q=80&w=800",
    price: 48,
    link: "/product/42",
    category: "aesthetic",
    rating: 4.8,
    reviews: 19,
  },
  {
    id: "43",
    name: "Slate Grey Hydration Bottle",
    blurb:
      "Matte finish, double-wall insulation. The understated accessory your desk needs.",
    img: "https://images.unsplash.com/photo-1718210719917-c6e1cd5be085?auto=format&fit=crop&q=80&w=800",
    price: 36,
    link: "/product/43",
    category: "water-bottles",
    rating: 4.3,
    reviews: 28,
  },
  {
    id: "44",
    name: "Midnight Silk Sleeping Mask",
    blurb:
      "Block out the world in total darkness. Pure silk that protects your lashes and skin while you dream.",
    img: "https://images.unsplash.com/photo-1546471180-335a013cb87b?fm=jpg&q=80&w=800",
    price: 25,
    link: "/product/44",
    category: "aesthetic",
    rating: 4.8,
    reviews: 42,
  },
  {
    id: "45",
    name: "Copper Pour-Over Kettle",
    blurb:
      "Precision pouring with a vintage shine. A barista-level tool that looks beautiful on your stove.",
    img: "https://images.unsplash.com/photo-1572048572872-2394404cf1f3?fm=jpg&q=80&w=800",
    price: 55,
    link: "/product/45",
    category: "home-decor",
    rating: 4.7,
    reviews: 18,
  },
  {
    id: "46",
    name: "Charcoal Detox Scrub",
    blurb:
      "Activated charcoal that draws out impurities. A gritty, satisfying scrub for deep-cleaned skin.",
    img: "https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?fm=jpg&q=80&w=800",
    price: 20,
    link: "/product/46",
    category: "cosmetics",
    rating: 4.4,
    reviews: 35,
  },
  {
    id: "47",
    name: "Glass Infuser Bottle",
    blurb:
      "Brew tea or fruit water on the go. Double-walled glass that shows off your drink's vibrant colors.",
    img: "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?fm=jpg&q=80&w=800",
    price: 28,
    link: "/product/47",
    category: "water-bottles",
    rating: 4.6,
    reviews: 22,
  },
  {
    id: "48",
    name: "Bamboo Bath Caddy",
    blurb:
      "Turn your tub into a spa. Holds your book, wine, and candle for the ultimate soak.",
    img: "https://images.unsplash.com/photo-1615873968403-89e068629265?fm=jpg&q=80&w=800",
    price: 42,
    link: "/product/48",
    category: "home-decor",
    rating: 4.9,
    reviews: 50,
  },
  {
    id: "49",
    name: "Vitamin C Radiance Serum",
    blurb:
      "A daily glow-up in a bottle. Brightens dark spots and evens skin tone with every drop.",
    img: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?fm=jpg&q=80&w=800",
    price: 32,
    link: "/product/49",
    category: "cosmetics",
    rating: 4.5,
    reviews: 29,
  },
  {
    id: "50",
    name: "Minimalist Desk Lamp",
    blurb:
      "Sleek lines and adjustable warm light. A focus-enhancing companion for late-night work.",
    img: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?fm=jpg&q=80&w=800",
    price: 48,
    link: "/product/50",
    category: "home-decor",
    rating: 4.3,
    reviews: 15,
  },
  {
    id: "51",
    name: "Weighted Knit Blanket",
    blurb:
      "Heavy, chunky knit that feels like a hug. Reduces anxiety and looks stunning on the sofa.",
    img: "https://images.unsplash.com/photo-1568191009535-7d8b407d389a?fm=jpg&q=80&w=800",
    price: 120,
    link: "/product/51",
    category: "aesthetic",
    rating: 4.9,
    reviews: 65,
  },
  {
    id: "52",
    name: "Hydro-Gel Face Mask Pack",
    blurb:
      "Instant hydration for tired skin. Cools on contact and leaves you looking dewy and rested.",
    img: "https://images.unsplash.com/photo-1605682681666-f4f47c6e4bb2?fm=jpg&q=80&w=800",
    price: 18,
    link: "/product/52",
    category: "cosmetics",
    rating: 4.2,
    reviews: 40,
  },
  {
    id: "53",
    name: "Insulated Travel Tumbler",
    blurb:
      "Vacuum sealed to keep coffee hot for hours. Spill-proof lid for streamlined commuting.",
    img: "https://images.unsplash.com/photo-1544003484-3cd181d17917?fm=jpg&q=80&w=800",
    price: 26,
    link: "/product/53",
    category: "water-bottles",
    rating: 4.5,
    reviews: 33,
  },
  {
    id: "54",
    name: "Eucalyptus Shower Bundle",
    blurb:
      "Fresh eucalyptus stems that release healing vapors in the steam. A natural respiratory relief.",
    img: "https://images.unsplash.com/photo-1628152371231-936cf45eb8f3?fm=jpg&q=80&w=800",
    price: 24,
    link: "/product/54",
    category: "home-decor",
    rating: 4.7,
    reviews: 21,
  },
  {
    id: "55",
    name: "Matte Black Lip Stain",
    blurb:
      "Bold, gothic elegance. A non-drying formula that stays pitch black all night long.",
    img: "https://images.unsplash.com/photo-1686831758227-1802d0ba5eda?fm=jpg&q=80&w=800",
    price: 22,
    link: "/product/55",
    category: "cosmetics",
    rating: 4.1,
    reviews: 12,
  },
  {
    id: "56",
    name: "Ceramic Stone Diffuser",
    blurb:
      "Ultrasonic mist that fills your room with scent. Matte stone finish that blends into any decor.",
    img: "https://images.unsplash.com/photo-1667312939978-64cf31718a6e?fm=jpg&q=80&w=800",
    price: 45,
    link: "/product/56",
    category: "home-decor",
    rating: 4.6,
    reviews: 38,
  },
  {
    id: "57",
    name: "Borosilicate Glass Straws",
    blurb:
      "Reusable, durable, and chic. A sustainable switch that makes every drink feel fancier.",
    img: "https://images.unsplash.com/photo-1617972882867-3707f274c115?fm=jpg&q=80&w=800",
    price: 15,
    link: "/product/57",
    category: "aesthetic",
    rating: 4.8,
    reviews: 55,
  },
  {
    id: "58",
    name: "Collapsible Silicon Bottle",
    blurb:
      "Folds down flat when empty. The ultimate space-saver for travel and hiking.",
    img: "https://images.unsplash.com/photo-1616118133712-8c947f7b822c?fm=jpg&q=80&w=800",
    price: 22,
    link: "/product/58",
    category: "water-bottles",
    rating: 4.3,
    reviews: 19,
  },
  {
    id: "59",
    name: "Himalayan Salt Lamp",
    blurb:
      "Warm, amber glow that purifies the air. Creates a cozy, relaxing atmosphere instantly.",
    img: "https://images.unsplash.com/photo-1504253492562-cbc4dc540fcb?fm=jpg&q=80&w=800",
    price: 29,
    link: "/product/59",
    category: "aesthetic",
    rating: 4.7,
    reviews: 45,
  },
  {
    id: "60",
    name: "Retinol Night Cream",
    blurb:
      "Powerhouse anti-aging while you sleep. Wakes up plumper, smoother skin.",
    img: "https://images.unsplash.com/photo-1686831451322-8d8e234a51e1?fm=jpg&q=80&w=800",
    price: 38,
    link: "/product/60",
    category: "cosmetics",
    rating: 4.5,
    reviews: 26,
  },
  {
    id: "61",
    name: "Floating Wall Shelves",
    blurb:
      "Invisible mounting for a clean, modern look. Perfect for displaying plants and photos.",
    img: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?fm=jpg&q=80&w=800",
    price: 35,
    link: "/product/61",
    category: "home-decor",
    rating: 4.2,
    reviews: 17,
  },
  {
    id: "62",
    name: "Smart Hydration Tracker",
    blurb:
      "Glows to remind you to drink. Syncs with your phone to track your daily water intake.",
    img: "https://images.unsplash.com/photo-1664714628878-9d2aa898b9e3?fm=jpg&q=80&w=800",
    price: 65,
    link: "/product/62",
    category: "water-bottles",
    rating: 4.0,
    reviews: 9,
  },
  {
    id: "63",
    name: "Linen Throw Pillow",
    blurb:
      "Stonewashed linen for a soft, lived-in texture. Earthy tones that ground your living space.",
    img: "https://images.unsplash.com/photo-1766245456897-5c86726d084d?w=1080",
    price: 28,
    link: "/product/63",
    category: "aesthetic",
    rating: 4.6,
    reviews: 31,
  },
  {
    id: "64",
    name: "Rose Quartz Facial Roller",
    blurb:
      "Promote circulation and encourage skin rejuvenation with this cooling rose quartz tool.",
    img: "https://images.unsplash.com/photo-1600428853876-fb5a850b444f?auto=format&fit=crop&q=80&w=1080",
    price: 28,
    link: "/product/64",
    category: "cosmetics",
    rating: 4.6,
    reviews: 52,
  },
  {
    id: "65",
    name: "Hydrating Mist Toner",
    blurb:
      "A burst of freshness with aloe and rosewater. Instantly revitalizes dry, tired skin.",
    img: "https://images.unsplash.com/photo-1601066551508-6d9cb1b9de65?auto=format&fit=crop&q=80&w=1080",
    price: 22,
    link: "/product/65",
    category: "cosmetics",
    rating: 4.4,
    reviews: 19,
  },
  {
    id: "66",
    name: "Golden Glow Body Oil",
    blurb:
      "Shimmering body oil that leaves a sun-kissed finish. Fast-absorbing and non-greasy.",
    img: "https://images.unsplash.com/photo-1702724122793-37ff49fee252?auto=format&fit=crop&q=80&w=1080",
    price: 34,
    link: "/product/66",
    category: "cosmetics",
    rating: 4.8,
    reviews: 63,
  },
  {
    id: "67",
    name: "Pro-Collagen Eye Cream",
    blurb:
      "Target fine lines and dark circles. A lightweight formula that smooths and brightens.",
    img: "https://images.unsplash.com/photo-1594813591867-02e797aa4581?auto=format&fit=crop&q=80&w=1080",
    price: 45,
    link: "/product/67",
    category: "cosmetics",
    rating: 4.7,
    reviews: 30,
  },
  {
    id: "68",
    name: "Silk Peptide Foundation",
    blurb:
      "Buildable coverage with a skin-like finish. Infused with silk peptides for a soft glow.",
    img: "https://images.unsplash.com/photo-1512207683547-2631a3798786?auto=format&fit=crop&q=80&w=1080",
    price: 38,
    link: "/product/68",
    category: "cosmetics",
    rating: 4.5,
    reviews: 41,
  },
  {
    id: "69",
    name: "Nordic Ceramic Vase",
    blurb:
      "Simple, organic curves in a matte finish. A statement piece for minimalism lovers.",
    img: "https://images.unsplash.com/photo-1575783389521-f2e87b4f994a?w=1080",
    price: 42,
    link: "/product/69",
    category: "home-decor",
    rating: 4.9,
    reviews: 25,
  },
  {
    id: "70",
    name: "Velvet Accent Chair",
    blurb:
      "Luxurious velvet upholstery in a jewel tone. Adds a pop of color and comfort to any corner.",
    img: "https://images.unsplash.com/photo-1765663241884-ebd171bdda1d?w=1080",
    price: 185,
    link: "/product/70",
    category: "home-decor",
    rating: 4.7,
    reviews: 14,
  },
  {
    id: "71",
    name: "Geometric Wall Mirror",
    blurb:
      "Modern brass frame with a unique shape. Reflects light and opens up your space.",
    img: "https://images.unsplash.com/photo-1729160010511-a996a95c0475?w=1080",
    price: 95,
    link: "/product/71",
    category: "home-decor",
    rating: 4.8,
    reviews: 36,
  },
  {
    id: "72",
    name: "Live Edge Coffee Table",
    blurb:
      "Raw wood edge meets industrial metal legs. Each piece is unique and full of character.",
    img: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=1080",
    price: 250,
    link: "/product/72",
    category: "home-decor",
    rating: 5.0,
    reviews: 8,
  },
  {
    id: "73",
    name: "Handwoven Jute Rug",
    blurb:
      "Natural fibers and texture for a grounded feel. Durable and perfect for high-traffic areas.",
    img: "https://images.unsplash.com/photo-1762758889413-64d717f81b0d?w=1080",
    price: 120,
    link: "/product/73",
    category: "home-decor",
    rating: 4.6,
    reviews: 22,
  },
  {
    id: "74",
    name: "Crystal Elixir Bottle",
    blurb:
      "Infuse your water with good vibes. Features a genuine quartz point inside the glass chamber.",
    img: "https://images.unsplash.com/photo-1606756805780-b51ae7de41a9?w=1080",
    price: 58,
    link: "/product/74",
    category: "water-bottles",
    rating: 4.3,
    reviews: 15,
  },
  {
    id: "75",
    name: "Smart Temperature Bottle",
    blurb:
      "LED lid displays internal temperature. Keep your coffee piping hot or water ice cold.",
    img: "https://images.unsplash.com/photo-1585250815365-a90a469677c5?w=1080",
    price: 45,
    link: "/product/75",
    category: "water-bottles",
    rating: 4.5,
    reviews: 28,
  },
  {
    id: "76",
    name: "Wide Mouth Sport Flask",
    blurb:
      "Rugged design with a powder-coat finish. The wide mouth makes adding ice breeze.",
    img: "https://images.unsplash.com/photo-1616740540792-3daec604777d?w=1080",
    price: 32,
    link: "/product/76",
    category: "water-bottles",
    rating: 4.8,
    reviews: 70,
  },
  {
    id: "77",
    name: "Glass Smoothie Tumbler",
    blurb:
      "Protective silicone sleeve and wide straw. Perfect for thick smoothies and shakes on the go.",
    img: "https://images.unsplash.com/photo-1571161473325-1594dece4499?w=1080",
    price: 24,
    link: "/product/77",
    category: "water-bottles",
    rating: 4.6,
    reviews: 33,
  },
  {
    id: "78",
    name: "Matte Finish Thermos",
    blurb:
      "Double-walled insulation in a sleek matte shell. Keeps drinks stable for 12+ hours.",
    img: "https://images.unsplash.com/photo-1550736386-78b14d2601f8?w=1080",
    price: 28,
    link: "/product/78",
    category: "water-bottles",
    rating: 4.4,
    reviews: 21,
  },
  {
    id: "79",
    name: "Sunset Projection Lamp",
    blurb:
      "Bring the golden hour inside. Projects a warm, calming circle of light onto your wall.",
    img: "https://images.unsplash.com/photo-1662389943926-d65c240a86a5?w=1080",
    price: 25,
    link: "/product/79",
    category: "aesthetic",
    rating: 4.2,
    reviews: 45,
  },
  {
    id: "80",
    name: "Vintage Vinyl Player",
    blurb:
      "Modern tech with retro soul. Belt-driven turntable with built-in speakers for instant vibes.",
    img: "https://images.unsplash.com/photo-1624374021599-2806783f8d4a?w=1080",
    price: 150,
    link: "/product/80",
    category: "aesthetic",
    rating: 4.9,
    reviews: 80,
  },
  {
    id: "81",
    name: "Neon Cloud Light",
    blurb:
      "Dreamy playful decor. A soft LED neon sign that adds a whimsical touch to your room.",
    img: "https://images.unsplash.com/photo-1595981234522-aa6bae3f0dac?w=1080",
    price: 30,
    link: "/product/81",
    category: "aesthetic",
    rating: 4.5,
    reviews: 18,
  },
  {
    id: "82",
    name: "Instax Mini Photo Album",
    blurb:
      "Preserve your memories in style. A cute, pocket-sized album for your instant prints.",
    img: "https://images.unsplash.com/photo-1641305286488-03be4d517a4f?w=1080",
    price: 15,
    link: "/product/82",
    category: "aesthetic",
    rating: 4.7,
    reviews: 29,
  },
  {
    id: "83",
    name: "Kinfolk Coffee Table Book",
    blurb:
      "The quintessential aesthetic tome. Beautiful photography and essays on slow living.",
    img: "https://images.unsplash.com/photo-1544816155-12df964ac73c?w=1080",
    price: 40,
    link: "/product/83",
    category: "aesthetic",
    rating: 4.8,
    reviews: 55,
  },
  {
    id: "84",
    name: "Vitamin E Face Oil",
    blurb:
      "Deeply restorative oil that repairs and glows. A few drops is all you need for radiance.",
    img: "https://images.unsplash.com/photo-1741896135512-084b251887f7?w=1080",
    price: 32,
    link: "/product/84",
    category: "cosmetics",
    rating: 4.8,
    reviews: 24,
  },
  {
    id: "85",
    name: "Volcanic Ash Clay Mask",
    blurb:
      "Detoxify your pores with raw volcanic earth. Leaves skin feeling tight, clean, and renewed.",
    img: "https://images.unsplash.com/photo-1710693547912-db17dc079ed4?w=1080",
    price: 26,
    link: "/product/85",
    category: "cosmetics",
    rating: 4.6,
    reviews: 31,
  },
  {
    id: "86",
    name: "Bamboo Toothbrush Set",
    blurb:
      "Sustainable oral care. Biodegradable bamboo handles with soft charcoal-infused bristles.",
    img: "https://images.unsplash.com/photo-1592372554345-22ced975691d?w=1080",
    price: 14,
    link: "/product/86",
    category: "cosmetics",
    rating: 4.9,
    reviews: 50,
  },
  {
    id: "87",
    name: "Solid Perfume Balm",
    blurb:
      "A pocket-sized scent for touch-ups on the go. Subtle, waxy, and intimate.",
    img: "https://images.unsplash.com/photo-1656103743126-656ce0ed6291?w=1080",
    price: 22,
    link: "/product/87",
    category: "cosmetics",
    rating: 4.4,
    reviews: 18,
  },
  {
    id: "88",
    name: "Coconut Milk Bath Soak",
    blurb:
      "Creamy, hydrating escape. Turns your bath water into a silky, moisturizing cloud.",
    img: "https://images.unsplash.com/photo-1724155593611-68a596dcc9ed?w=1080",
    price: 28,
    link: "/product/88",
    category: "cosmetics",
    rating: 4.8,
    reviews: 42,
  },
  {
    id: "89",
    name: "Macrame Wall Hanging",
    blurb:
      "Bohemian texture for your sanctuary. Intricate knots that add softness to bare walls.",
    img: "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1080",
    price: 45,
    link: "/product/89",
    category: "home-decor",
    rating: 4.7,
    reviews: 29,
  },
  {
    id: "90",
    name: "Terrazzo Coasters",
    blurb:
      "Art for your table. Speckled stone composite that keeps surfaces dry and stylish.",
    img: "https://images.unsplash.com/photo-1620610520335-5120613769c7?w=1080",
    price: 24,
    link: "/product/90",
    category: "home-decor",
    rating: 4.5,
    reviews: 21,
  },
  {
    id: "91",
    name: "Brass Incense Holder",
    blurb:
      "Minimalist metal sculpture. Catches ash while elevating your fragrance ritual.",
    img: "https://images.unsplash.com/photo-1602872029708-84d970d32cb0?w=1080",
    price: 18,
    link: "/product/91",
    category: "home-decor",
    rating: 4.6,
    reviews: 35,
  },
  {
    id: "92",
    name: "Woven Seagrass Basket",
    blurb:
      "Organic storage that breathes. Perfect for blankets, plants, or clutter control.",
    img: "https://images.unsplash.com/photo-1594916244600-47963d8c6d32?w=1080",
    price: 36,
    link: "/product/92",
    category: "home-decor",
    rating: 4.8,
    reviews: 47,
  },
  {
    id: "93",
    name: "Ceramic Taper Candle Holder",
    blurb:
      "A single stem of ceramic to hold your evening light. Simple, matte, and beautiful.",
    img: "https://images.unsplash.com/photo-1621319330642-ef4775086851?w=1080",
    price: 22,
    link: "/product/93",
    category: "home-decor",
    rating: 4.7,
    reviews: 16,
  },
  {
    id: "94",
    name: "Marble Serving Board",
    blurb:
      "Cool, heavy white marble. The perfect backdrop for cheeses, fruits, and charcuterie.",
    img: "https://images.unsplash.com/photo-1596701062351-be5f6a422e91?w=1080",
    price: 55,
    link: "/product/94",
    category: "home-decor",
    rating: 4.9,
    reviews: 23,
  },
  {
    id: "95",
    name: "Linen Apron",
    blurb:
      "Chef quality with a cottage core soul. Durable linen that softens with every wash.",
    img: "https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=1080",
    price: 48,
    link: "/product/95",
    category: "home-decor",
    rating: 4.8,
    reviews: 38,
  },
  {
    id: "96",
    name: "Copper Measuring Cups",
    blurb:
      "Bake with brilliance. Heavy-gauge copper cups that make ingredients look precious.",
    img: "https://images.unsplash.com/photo-1621217646536-193951f9c061?w=1080",
    price: 34,
    link: "/product/96",
    category: "home-decor",
    rating: 4.6,
    reviews: 20,
  },
  {
    id: "97",
    name: "Speckled Ceramic Mug",
    blurb:
      "Your new favorite mug. Thick walls to keep heat in, with a comforting handmade feel.",
    img: "https://images.unsplash.com/photo-1577908906569-c6517a61fc0f?w=1080",
    price: 24,
    link: "/product/97",
    category: "home-decor",
    rating: 4.9,
    reviews: 82,
  },
  {
    id: "98",
    name: "Brass Tea Strainer",
    blurb:
      "Loose leaf luxury. A fine mesh brass sieve for the perfect cup of clarity.",
    img: "https://images.unsplash.com/photo-1597485454394-70171bb9915f?w=1080",
    price: 16,
    link: "/product/98",
    category: "home-decor",
    rating: 4.7,
    reviews: 28,
  },
  {
    id: "99",
    name: "Premium Yoga Mat",
    blurb:
      "Non-slip grip with aesthetic tones. Supportive cushioning for your daily flow.",
    img: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?w=1080",
    price: 65,
    link: "/product/99",
    category: "aesthetic",
    rating: 4.8,
    reviews: 54,
  },
  {
    id: "100",
    name: "Cork Yoga Block",
    blurb:
      "Sustainable support. Firm, natural cork that helps you reach deeper into every pose.",
    img: "https://images.unsplash.com/photo-1628102472412-81788730b205?w=1080",
    price: 22,
    link: "/product/100",
    category: "aesthetic",
    rating: 4.9,
    reviews: 31,
  },
  {
    id: "101",
    name: "Essential Oil Diffuser",
    blurb:
      "Ultrasonic mist technology. Quietly fills your room with the healing power of scent.",
    img: "https://images.unsplash.com/photo-1547333590-47fae5f58d21?w=1080",
    price: 48,
    link: "/product/101",
    category: "home-decor",
    rating: 4.7,
    reviews: 65,
  },
  {
    id: "102",
    name: "Meditation Cushion",
    blurb:
      "Sit comfortably, longer. Ergonomic floor pillow with buckwheat hull filling.",
    img: "https://images.unsplash.com/photo-1597307509190-e33cb9fb3ff7?w=1080",
    price: 52,
    link: "/product/102",
    category: "aesthetic",
    rating: 4.8,
    reviews: 24,
  },
  {
    id: "103",
    name: "Tibetan Singing Bowl",
    blurb:
      "Sound healing in your hands. Hand-hammered metal that resonates with pure, calming tones.",
    img: "https://images.unsplash.com/photo-1699708681177-f2730ca7fa7f?w=1080",
    price: 75,
    link: "/product/103",
    category: "aesthetic",
    rating: 4.9,
    reviews: 19,
  },
];

export const dynamicCategories = Array.from(
  new Set(products.map((p) => p.category))
);

export const categoryLabels: Record<Product["category"], string> = {
  cosmetics: "Cosmetics",
  "home-decor": "Home Decor",
  "water-bottles": "Water Bottles",
  aesthetic: "Aesthetic",
};
